services:
  scheduler:
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/usr/local/airflow/gcloud/application_default_credentials.json:rw
  api-server:
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/usr/local/airflow/gcloud/application_default_credentials.json:rw
  triggerer:
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/usr/local/airflow/gcloud/application_default_credentials.json:rw
  dag-processor:
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/usr/local/airflow/gcloud/application_default_credentials.json:rw